// src/utils/countries.js
export const countries = [
  { code: "AF", name: "Afghanistan", flag: "https://flagcdn.com/af.svg", phoneCode: "+93" },
  { code: "AL", name: "Albania", flag: "https://flagcdn.com/al.svg", phoneCode: "+355" },
  { code: "DZ", name: "Algeria", flag: "https://flagcdn.com/dz.svg", phoneCode: "+213" },
  { code: "AD", name: "Andorra", flag: "https://flagcdn.com/ad.svg", phoneCode: "+376" },
  { code: "AO", name: "Angola", flag: "https://flagcdn.com/ao.svg", phoneCode: "+244" },
  { code: "AG", name: "Antigua and Barbuda", flag: "https://flagcdn.com/ag.svg", phoneCode: "+1268" },
  { code: "AR", name: "Argentina", flag: "https://flagcdn.com/ar.svg", phoneCode: "+54" },
  { code: "AM", name: "Armenia", flag: "https://flagcdn.com/am.svg", phoneCode: "+374" },
  { code: "AU", name: "Australia", flag: "https://flagcdn.com/au.svg", phoneCode: "+61" },
  { code: "AT", name: "Austria", flag: "https://flagcdn.com/at.svg", phoneCode: "+43" },
  { code: "AZ", name: "Azerbaijan", flag: "https://flagcdn.com/az.svg", phoneCode: "+994" },
  { code: "BS", name: "Bahamas", flag: "https://flagcdn.com/bs.svg", phoneCode: "+1242" },
  { code: "BH", name: "Bahrain", flag: "https://flagcdn.com/bh.svg", phoneCode: "+973" },
  { code: "BD", name: "Bangladesh", flag: "https://flagcdn.com/bd.svg", phoneCode: "+880" },
  { code: "BB", name: "Barbados", flag: "https://flagcdn.com/bb.svg", phoneCode: "+1246" },
  { code: "BY", name: "Belarus", flag: "https://flagcdn.com/by.svg", phoneCode: "+375" },
  { code: "BE", name: "Belgium", flag: "https://flagcdn.com/be.svg", phoneCode: "+32" },
  { code: "BZ", name: "Belize", flag: "https://flagcdn.com/bz.svg", phoneCode: "+501" },
  { code: "BJ", name: "Benin", flag: "https://flagcdn.com/bj.svg", phoneCode: "+229" },
  { code: "BT", name: "Bhutan", flag: "https://flagcdn.com/bt.svg", phoneCode: "+975" },
  { code: "BO", name: "Bolivia", flag: "https://flagcdn.com/bo.svg", phoneCode: "+591" },
  { code: "BA", name: "Bosnia and Herzegovina", flag: "https://flagcdn.com/ba.svg", phoneCode: "+387" },
  { code: "BW", name: "Botswana", flag: "https://flagcdn.com/bw.svg", phoneCode: "+267" },
  { code: "BR", name: "Brazil", flag: "https://flagcdn.com/br.svg", phoneCode: "+55" },
  { code: "BN", name: "Brunei", flag: "https://flagcdn.com/bn.svg", phoneCode: "+673" },
  { code: "BG", name: "Bulgaria", flag: "https://flagcdn.com/bg.svg", phoneCode: "+359" },
  { code: "BF", name: "Burkina Faso", flag: "https://flagcdn.com/bf.svg", phoneCode: "+226" },
  { code: "BI", name: "Burundi", flag: "https://flagcdn.com/bi.svg", phoneCode: "+257" },
  { code: "CV", name: "Cabo Verde", flag: "https://flagcdn.com/cv.svg", phoneCode: "+238" },
  { code: "KH", name: "Cambodia", flag: "https://flagcdn.com/kh.svg", phoneCode: "+855" },
  { code: "CM", name: "Cameroon", flag: "https://flagcdn.com/cm.svg", phoneCode: "+237" },
  { code: "CA", name: "Canada", flag: "https://flagcdn.com/ca.svg", phoneCode: "+1" },
  { code: "CF", name: "Central African Republic", flag: "https://flagcdn.com/cf.svg", phoneCode: "+236" },
  { code: "TD", name: "Chad", flag: "https://flagcdn.com/td.svg", phoneCode: "+235" },
  { code: "CL", name: "Chile", flag: "https://flagcdn.com/cl.svg", phoneCode: "+56" },
  { code: "CN", name: "China", flag: "https://flagcdn.com/cn.svg", phoneCode: "+86" },
  { code: "CO", name: "Colombia", flag: "https://flagcdn.com/co.svg", phoneCode: "+57" },
  { code: "KM", name: "Comoros", flag: "https://flagcdn.com/km.svg", phoneCode: "+269" },
  { code: "CG", name: "Congo", flag: "https://flagcdn.com/cg.svg", phoneCode: "+242" },
  { code: "CR", name: "Costa Rica", flag: "https://flagcdn.com/cr.svg", phoneCode: "+506" },
  { code: "CI", name: "Côte d'Ivoire", flag: "https://flagcdn.com/ci.svg", phoneCode: "+225" },
  { code: "HR", name: "Croatia", flag: "https://flagcdn.com/hr.svg", phoneCode: "+385" },
  { code: "CU", name: "Cuba", flag: "https://flagcdn.com/cu.svg", phoneCode: "+53" },
  { code: "CY", name: "Cyprus", flag: "https://flagcdn.com/cy.svg", phoneCode: "+357" },
  { code: "CZ", name: "Czech Republic", flag: "https://flagcdn.com/cz.svg", phoneCode: "+420" },
  { code: "DK", name: "Denmark", flag: "https://flagcdn.com/dk.svg", phoneCode: "+45" },
  { code: "DJ", name: "Djibouti", flag: "https://flagcdn.com/dj.svg", phoneCode: "+253" },
  { code: "DM", name: "Dominica", flag: "https://flagcdn.com/dm.svg", phoneCode: "+1767" },
  { code: "DO", name: "Dominican Republic", flag: "https://flagcdn.com/do.svg", phoneCode: "+1849" },
  { code: "EC", name: "Ecuador", flag: "https://flagcdn.com/ec.svg", phoneCode: "+593" },
  { code: "EG", name: "Egypt", flag: "https://flagcdn.com/eg.svg", phoneCode: "+20" },
  { code: "SV", name: "El Salvador", flag: "https://flagcdn.com/sv.svg", phoneCode: "+503" },
  { code: "GQ", name: "Equatorial Guinea", flag: "https://flagcdn.com/gq.svg", phoneCode: "+240" },
  { code: "ER", name: "Eritrea", flag: "https://flagcdn.com/er.svg", phoneCode: "+291" },
  { code: "EE", name: "Estonia", flag: "https://flagcdn.com/ee.svg", phoneCode: "+372" },
  { code: "SZ", name: "Eswatini", flag: "https://flagcdn.com/sz.svg", phoneCode: "+268" },
  { code: "ET", name: "Ethiopia", flag: "https://flagcdn.com/et.svg", phoneCode: "+251" },
  { code: "FJ", name: "Fiji", flag: "https://flagcdn.com/fj.svg", phoneCode: "+679" },
  { code: "FI", name: "Finland", flag: "https://flagcdn.com/fi.svg", phoneCode: "+358" },
  { code: "FR", name: "France", flag: "https://flagcdn.com/fr.svg", phoneCode: "+33" },
  { code: "GA", name: "Gabon", flag: "https://flagcdn.com/ga.svg", phoneCode: "+241" },
  { code: "GM", name: "Gambia", flag: "https://flagcdn.com/gm.svg", phoneCode: "+220" },
  { code: "GE", name: "Georgia", flag: "https://flagcdn.com/ge.svg", phoneCode: "+995" },
  { code: "DE", name: "Germany", flag: "https://flagcdn.com/de.svg", phoneCode: "+49" },
  { code: "GH", name: "Ghana", flag: "https://flagcdn.com/gh.svg", phoneCode: "+233" },
  { code: "GR", name: "Greece", flag: "https://flagcdn.com/gr.svg", phoneCode: "+30" },
  { code: "GD", name: "Grenada", flag: "https://flagcdn.com/gd.svg", phoneCode: "+1473" },
  { code: "GT", name: "Guatemala", flag: "https://flagcdn.com/gt.svg", phoneCode: "+502" },
  { code: "GN", name: "Guinea", flag: "https://flagcdn.com/gn.svg", phoneCode: "+224" },
  { code: "GW", name: "Guinea-Bissau", flag: "https://flagcdn.com/gw.svg", phoneCode: "+245" },
  { code: "GY", name: "Guyana", flag: "https://flagcdn.com/gy.svg", phoneCode: "+592" },
  { code: "HT", name: "Haiti", flag: "https://flagcdn.com/ht.svg", phoneCode: "+509" },
  { code: "HN", name: "Honduras", flag: "https://flagcdn.com/hn.svg", phoneCode: "+504" },
  { code: "HU", name: "Hungary", flag: "https://flagcdn.com/hu.svg", phoneCode: "+36" },
  { code: "IS", name: "Iceland", flag: "https://flagcdn.com/is.svg", phoneCode: "+354" },
  { code: "IN", name: "India", flag: "https://flagcdn.com/in.svg", phoneCode: "+91" },
  { code: "ID", name: "Indonesia", flag: "https://flagcdn.com/id.svg", phoneCode: "+62" },
  { code: "IR", name: "Iran", flag: "https://flagcdn.com/ir.svg", phoneCode: "+98" },
  { code: "IQ", name: "Iraq", flag: "https://flagcdn.com/iq.svg", phoneCode: "+964" },
  { code: "IE", name: "Ireland", flag: "https://flagcdn.com/ie.svg", phoneCode: "+353" },
  { code: "IL", name: "Israel", flag: "https://flagcdn.com/il.svg", phoneCode: "+972" },
  { code: "IT", name: "Italy", flag: "https://flagcdn.com/it.svg", phoneCode: "+39" },
  { code: "JM", name: "Jamaica", flag: "https://flagcdn.com/jm.svg", phoneCode: "+1876" },
  { code: "JP", name: "Japan", flag: "https://flagcdn.com/jp.svg", phoneCode: "+81" },
  { code: "JO", name: "Jordan", flag: "https://flagcdn.com/jo.svg", phoneCode: "+962" },
  { code: "KZ", name: "Kazakhstan", flag: "https://flagcdn.com/kz.svg", phoneCode: "+7" },
  { code: "KE", name: "Kenya", flag: "https://flagcdn.com/ke.svg", phoneCode: "+254" },
  { code: "KI", name: "Kiribati", flag: "https://flagcdn.com/ki.svg", phoneCode: "+686" },
  { code: "KP", name: "North Korea", flag: "https://flagcdn.com/kp.svg", phoneCode: "+850" },
  { code: "KR", name: "South Korea", flag: "https://flagcdn.com/kr.svg", phoneCode: "+82" },
  { code: "KW", name: "Kuwait", flag: "https://flagcdn.com/kw.svg", phoneCode: "+965" },
  { code: "KG", name: "Kyrgyzstan", flag: "https://flagcdn.com/kg.svg", phoneCode: "+996" },
  { code: "LA", name: "Laos", flag: "https://flagcdn.com/la.svg", phoneCode: "+856" },
  { code: "LV", name: "Latvia", flag: "https://flagcdn.com/lv.svg", phoneCode: "+371" },
  { code: "LB", name: "Lebanon", flag: "https://flagcdn.com/lb.svg", phoneCode: "+961" },
  { code: "LS", name: "Lesotho", flag: "https://flagcdn.com/ls.svg", phoneCode: "+266" },
  { code: "LR", name: "Liberia", flag: "https://flagcdn.com/lr.svg", phoneCode: "+231" },
  { code: "LY", name: "Libya", flag: "https://flagcdn.com/ly.svg", phoneCode: "+218" },
  { code: "LI", name: "Liechtenstein", flag: "https://flagcdn.com/li.svg", phoneCode: "+423" },
  { code: "LT", name: "Lithuania", flag: "https://flagcdn.com/lt.svg", phoneCode: "+370" },
  { code: "LU", name: "Luxembourg", flag: "https://flagcdn.com/lu.svg", phoneCode: "+352" },
  { code: "MG", name: "Madagascar", flag: "https://flagcdn.com/mg.svg", phoneCode: "+261" },
  { code: "MW", name: "Malawi", flag: "https://flagcdn.com/mw.svg", phoneCode: "+265" },
  { code: "MY", name: "Malaysia", flag: "https://flagcdn.com/my.svg", phoneCode: "+60" },
  { code: "MV", name: "Maldives", flag: "https://flagcdn.com/mv.svg", phoneCode: "+960" },
  { code: "ML", name: "Mali", flag: "https://flagcdn.com/ml.svg", phoneCode: "+223" },
  { code: "MT", name: "Malta", flag: "https://flagcdn.com/mt.svg", phoneCode: "+356" },
  { code: "MH", name: "Marshall Islands", flag: "https://flagcdn.com/mh.svg", phoneCode: "+692" },
  { code: "MR", name: "Mauritania", flag: "https://flagcdn.com/mr.svg", phoneCode: "+222" },
  { code: "MU", name: "Mauritius", flag: "https://flagcdn.com/mu.svg", phoneCode: "+230" },
  { code: "MX", name: "Mexico", flag: "https://flagcdn.com/mx.svg", phoneCode: "+52" },
  { code: "FM", name: "Micronesia", flag: "https://flagcdn.com/fm.svg", phoneCode: "+691" },
  { code: "MD", name: "Moldova", flag: "https://flagcdn.com/md.svg", phoneCode: "+373" },
  { code: "MC", name: "Monaco", flag: "https://flagcdn.com/mc.svg", phoneCode: "+377" },
  { code: "MN", name: "Mongolia", flag: "https://flagcdn.com/mn.svg", phoneCode: "+976" },
  { code: "ME", name: "Montenegro", flag: "https://flagcdn.com/me.svg", phoneCode: "+382" },
  { code: "MA", name: "Morocco", flag: "https://flagcdn.com/ma.svg", phoneCode: "+212" },
  { code: "MZ", name: "Mozambique", flag: "https://flagcdn.com/mz.svg", phoneCode: "+258" },
  { code: "MM", name: "Myanmar", flag: "https://flagcdn.com/mm.svg", phoneCode: "+95" },
  { code: "NA", name: "Namibia", flag: "https://flagcdn.com/na.svg", phoneCode: "+264" },
  { code: "NR", name: "Nauru", flag: "https://flagcdn.com/nr.svg", phoneCode: "+674" },
  { code: "NP", name: "Nepal", flag: "https://flagcdn.com/np.svg", phoneCode: "+977" },
  { code: "NL", name: "Netherlands", flag: "https://flagcdn.com/nl.svg", phoneCode: "+31" },
  { code: "NZ", name: "New Zealand", flag: "https://flagcdn.com/nz.svg", phoneCode: "+64" },
  { code: "NI", name: "Nicaragua", flag: "https://flagcdn.com/ni.svg", phoneCode: "+505" },
  { code: "NE", name: "Niger", flag: "https://flagcdn.com/ne.svg", phoneCode: "+227" },
  { code: "NG", name: "Nigeria", flag: "https://flagcdn.com/ng.svg", phoneCode: "+234" },
  { code: "NO", name: "Norway", flag: "https://flagcdn.com/no.svg", phoneCode: "+47" },
  { code: "OM", name: "Oman", flag: "https://flagcdn.com/om.svg", phoneCode: "+968" },
  { code: "PK", name: "Pakistan", flag: "https://flagcdn.com/pk.svg", phoneCode: "+92" },
  { code: "PW", name: "Palau", flag: "https://flagcdn.com/pw.svg", phoneCode: "+680" },
  { code: "PA", name: "Panama", flag: "https://flagcdn.com/pa.svg", phoneCode: "+507" },
  { code: "PG", name: "Papua New Guinea", flag: "https://flagcdn.com/pg.svg", phoneCode: "+675" },
  { code: "PY", name: "Paraguay", flag: "https://flagcdn.com/py.svg", phoneCode: "+595" },
  { code: "PE", name: "Peru", flag: "https://flagcdn.com/pe.svg", phoneCode: "+51" },
  { code: "PH", name: "Philippines", flag: "https://flagcdn.com/ph.svg", phoneCode: "+63" },
  { code: "PL", name: "Poland", flag: "https://flagcdn.com/pl.svg", phoneCode: "+48" },
  { code: "PT", name: "Portugal", flag: "https://flagcdn.com/pt.svg", phoneCode: "+351" },
  { code: "QA", name: "Qatar", flag: "https://flagcdn.com/qa.svg", phoneCode: "+974" },
  { code: "RO", name: "Romania", flag: "https://flagcdn.com/ro.svg", phoneCode: "+40" },
  { code: "RU", name: "Russia", flag: "https://flagcdn.com/ru.svg", phoneCode: "+7" },
  { code: "RW", name: "Rwanda", flag: "https://flagcdn.com/rw.svg", phoneCode: "+250" },
  { code: "KN", name: "Saint Kitts and Nevis", flag: "https://flagcdn.com/kn.svg", phoneCode: "+1869" },
  { code: "LC", name: "Saint Lucia", flag: "https://flagcdn.com/lc.svg", phoneCode: "+1758" },
  { code: "VC", name: "Saint Vincent and the Grenadines", flag: "https://flagcdn.com/vc.svg", phoneCode: "+1784" },
  { code: "WS", name: "Samoa", flag: "https://flagcdn.com/ws.svg", phoneCode: "+685" },
  { code: "SM", name: "San Marino", flag: "https://flagcdn.com/sm.svg", phoneCode: "+378" },
  { code: "ST", name: "Sao Tome and Principe", flag: "https://flagcdn.com/st.svg", phoneCode: "+239" },
  { code: "SA", name: "Saudi Arabia", flag: "https://flagcdn.com/sa.svg", phoneCode: "+966" },
  { code: "SN", name: "Senegal", flag: "https://flagcdn.com/sn.svg", phoneCode: "+221" },
  { code: "RS", name: "Serbia", flag: "https://flagcdn.com/rs.svg", phoneCode: "+381" },
  { code: "SC", name: "Seychelles", flag: "https://flagcdn.com/sc.svg", phoneCode: "+248" },
  { code: "SL", name: "Sierra Leone", flag: "https://flagcdn.com/sl.svg", phoneCode: "+232" },
  { code: "SG", name: "Singapore", flag: "https://flagcdn.com/sg.svg", phoneCode: "+65" },
  { code: "SK", name: "Slovakia", flag: "https://flagcdn.com/sk.svg", phoneCode: "+421" },
  { code: "SI", name: "Slovenia", flag: "https://flagcdn.com/si.svg", phoneCode: "+386" },
  { code: "SB", name: "Solomon Islands", flag: "https://flagcdn.com/sb.svg", phoneCode: "+677" },
  { code: "SO", name: "Somalia", flag: "https://flagcdn.com/so.svg", phoneCode: "+252" },
  { code: "ZA", name: "South Africa", flag: "https://flagcdn.com/za.svg", phoneCode: "+27" },
  { code: "SS", name: "South Sudan", flag: "https://flagcdn.com/ss.svg", phoneCode: "+211" },
  { code: "ES", name: "Spain", flag: "https://flagcdn.com/es.svg", phoneCode: "+34" },
  { code: "LK", name: "Sri Lanka", flag: "https://flagcdn.com/lk.svg", phoneCode: "+94" },
  { code: "SD", name: "Sudan", flag: "https://flagcdn.com/sd.svg", phoneCode: "+249" },
  { code: "SR", name: "Suriname", flag: "https://flagcdn.com/sr.svg", phoneCode: "+597" },
  { code: "SE", name: "Sweden", flag: "https://flagcdn.com/se.svg", phoneCode: "+46" },
  { code: "CH", name: "Switzerland", flag: "https://flagcdn.com/ch.svg", phoneCode: "+41" },
  { code: "SY", name: "Syria", flag: "https://flagcdn.com/sy.svg", phoneCode: "+963" },
  { code: "TW", name: "Taiwan", flag: "https://flagcdn.com/tw.svg", phoneCode: "+886" },
  { code: "TJ", name: "Tajikistan", flag: "https://flagcdn.com/tj.svg", phoneCode: "+992" },
  { code: "TZ", name: "Tanzania", flag: "https://flagcdn.com/tz.svg", phoneCode: "+255" },
  { code: "TH", name: "Thailand", flag: "https://flagcdn.com/th.svg", phoneCode: "+66" },
  { code: "TL", name: "Timor-Leste", flag: "https://flagcdn.com/tl.svg", phoneCode: "+670" },
  { code: "TG", name: "Togo", flag: "https://flagcdn.com/tg.svg", phoneCode: "+228" },
  { code: "TO", name: "Tonga", flag: "https://flagcdn.com/to.svg", phoneCode: "+676" },
  { code: "TT", name: "Trinidad and Tobago", flag: "https://flagcdn.com/tt.svg", phoneCode: "+1868" },
  { code: "TN", name: "Tunisia", flag: "https://flagcdn.com/tn.svg", phoneCode: "+216" },
  { code: "TR", name: "Turkey", flag: "https://flagcdn.com/tr.svg", phoneCode: "+90" },
  { code: "TM", name: "Turkmenistan", flag: "https://flagcdn.com/tm.svg", phoneCode: "+993" },
  { code: "TV", name: "Tuvalu", flag: "https://flagcdn.com/tv.svg", phoneCode: "+688" },
  { code: "UG", name: "Uganda", flag: "https://flagcdn.com/ug.svg", phoneCode: "+256" },
  { code: "UA", name: "Ukraine", flag: "https://flagcdn.com/ua.svg", phoneCode: "+380" },
  { code: "AE", name: "United Arab Emirates", flag: "https://flagcdn.com/ae.svg", phoneCode: "+971" },
  { code: "GB", name: "United Kingdom", flag: "https://flagcdn.com/gb.svg", phoneCode: "+44" },
  { code: "US", name: "United States", flag: "https://flagcdn.com/us.svg", phoneCode: "+1" },
  { code: "UY", name: "Uruguay", flag: "https://flagcdn.com/uy.svg", phoneCode: "+598" },
  { code: "UZ", name: "Uzbekistan", flag: "https://flagcdn.com/uz.svg", phoneCode: "+998" },
  { code: "VU", name: "Vanuatu", flag: "https://flagcdn.com/vu.svg", phoneCode: "+678" },
  { code: "VA", name: "Vatican City", flag: "https://flagcdn.com/va.svg", phoneCode: "+379" },
  { code: "VE", name: "Venezuela", flag: "https://flagcdn.com/ve.svg", phoneCode: "+58" },
  { code: "VN", name: "Vietnam", flag: "https://flagcdn.com/vn.svg", phoneCode: "+84" },
  { code: "YE", name: "Yemen", flag: "https://flagcdn.com/ye.svg", phoneCode: "+967" },
  { code: "ZM", name: "Zambia", flag: "https://flagcdn.com/zm.svg", phoneCode: "+260" },
  { code: "ZW", name: "Zimbabwe", flag: "https://flagcdn.com/zw.svg", phoneCode: "+263" }
];

export const getCountryByCode = (code) => {
  return countries.find(country => country.code === code) || countries[0];
};

export const getCountryByName = (name) => {
  return countries.find(country => country.name === name) || countries[0];
};